import { scoreNetwork } from "./risk";
import type { SupplyLink, SupplyNetwork, SupplyNode } from "./types";

interface NodeSeed {
  id: string;
  label: string;
  type: SupplyNode["type"];
  region: string;
  volume: number;
  leadTimeDays: number;
  bufferDays: number;
  recoveryDays: number;
  capacityUtilization: number;
  financialHealth: number;
}

const node = (seed: NodeSeed): SupplyNode => ({
  ...seed,
  status: "healthy",
  risk_score: 0, // derived by the risk model in scoreNetwork()
});

const seeds: NodeSeed[] = [
  // Tier 3 — raw materials
  {
    id: "R1",
    label: "Anhui Lithium Works",
    type: "raw",
    region: "Anhui, CN",
    volume: 4200,
    leadTimeDays: 34,
    bufferDays: 6,
    recoveryDays: 28,
    capacityUtilization: 0.93,
    financialHealth: 58,
  },
  {
    id: "R2",
    label: "Katanga Cobalt Co.",
    type: "raw",
    region: "Katanga, CD",
    volume: 2600,
    leadTimeDays: 46,
    bufferDays: 4,
    recoveryDays: 40,
    capacityUtilization: 0.95,
    financialHealth: 41,
  },
  {
    id: "R3",
    label: "Nordkraft Copper",
    type: "raw",
    region: "Kiruna, SE",
    volume: 5100,
    leadTimeDays: 18,
    bufferDays: 16,
    recoveryDays: 12,
    capacityUtilization: 0.68,
    financialHealth: 86,
  },
  {
    id: "R4",
    label: "Bahia Rare Earths",
    type: "raw",
    region: "Bahia, BR",
    volume: 1900,
    leadTimeDays: 29,
    bufferDays: 7,
    recoveryDays: 24,
    capacityUtilization: 0.88,
    financialHealth: 62,
  },
  {
    id: "R5",
    label: "Kyushu Silicon Refinery",
    type: "raw",
    region: "Kyushu, JP",
    volume: 3800,
    leadTimeDays: 21,
    bufferDays: 9,
    recoveryDays: 22,
    capacityUtilization: 0.91,
    financialHealth: 79,
  },
  {
    id: "R6",
    label: "Gujarat Polymer Feedstock",
    type: "raw",
    region: "Gujarat, IN",
    volume: 4600,
    leadTimeDays: 25,
    bufferDays: 12,
    recoveryDays: 15,
    capacityUtilization: 0.77,
    financialHealth: 70,
  },
  {
    id: "R7",
    label: "Ontario Alloy Mills",
    type: "raw",
    region: "Ontario, CA",
    volume: 3300,
    leadTimeDays: 12,
    bufferDays: 18,
    recoveryDays: 9,
    capacityUtilization: 0.62,
    financialHealth: 88,
  },
  {
    id: "R8",
    label: "Saxony Glass Sands",
    type: "raw",
    region: "Saxony, DE",
    volume: 2100,
    leadTimeDays: 14,
    bufferDays: 14,
    recoveryDays: 10,
    capacityUtilization: 0.7,
    financialHealth: 84,
  },

  // Tier 2 — component manufacturers
  {
    id: "C1",
    label: "Shenzhen Cell Fabrication",
    type: "component",
    region: "Shenzhen, CN",
    volume: 3600,
    leadTimeDays: 26,
    bufferDays: 8,
    recoveryDays: 21,
    capacityUtilization: 0.9,
    financialHealth: 64,
  },
  {
    id: "C2",
    label: "Hanoi Wire Harness",
    type: "component",
    region: "Hanoi, VN",
    volume: 2900,
    leadTimeDays: 19,
    bufferDays: 11,
    recoveryDays: 14,
    capacityUtilization: 0.74,
    financialHealth: 72,
  },
  {
    id: "C3",
    label: "Taipei Logic Foundry",
    type: "component",
    region: "Hsinchu, TW",
    volume: 2400,
    leadTimeDays: 38,
    bufferDays: 5,
    recoveryDays: 34,
    capacityUtilization: 0.97,
    financialHealth: 81,
  },
  {
    id: "C4",
    label: "Penang Sensor Systems",
    type: "component",
    region: "Penang, MY",
    volume: 2200,
    leadTimeDays: 22,
    bufferDays: 10,
    recoveryDays: 16,
    capacityUtilization: 0.78,
    financialHealth: 75,
  },
  {
    id: "C5",
    label: "Pune Housing Molds",
    type: "component",
    region: "Pune, IN",
    volume: 3100,
    leadTimeDays: 16,
    bufferDays: 13,
    recoveryDays: 11,
    capacityUtilization: 0.71,
    financialHealth: 77,
  },
  {
    id: "C6",
    label: "Monterrey Casting Group",
    type: "component",
    region: "Monterrey, MX",
    volume: 2700,
    leadTimeDays: 11,
    bufferDays: 15,
    recoveryDays: 8,
    capacityUtilization: 0.66,
    financialHealth: 82,
  },
  {
    id: "C7",
    label: "Kraków Display Panels",
    type: "component",
    region: "Kraków, PL",
    volume: 1800,
    leadTimeDays: 20,
    bufferDays: 9,
    recoveryDays: 17,
    capacityUtilization: 0.8,
    financialHealth: 73,
  },
  {
    id: "C8",
    label: "Busan Magnet Industries",
    type: "component",
    region: "Busan, KR",
    volume: 1500,
    leadTimeDays: 24,
    bufferDays: 7,
    recoveryDays: 19,
    capacityUtilization: 0.86,
    financialHealth: 68,
  },

  // Tier 1 — sub-assembly
  {
    id: "S1",
    label: "Chongqing Battery Modules",
    type: "subassembly",
    region: "Chongqing, CN",
    volume: 3200,
    leadTimeDays: 17,
    bufferDays: 8,
    recoveryDays: 15,
    capacityUtilization: 0.89,
    financialHealth: 66,
  },
  {
    id: "S2",
    label: "Bratislava Control Units",
    type: "subassembly",
    region: "Bratislava, SK",
    volume: 2500,
    leadTimeDays: 13,
    bufferDays: 12,
    recoveryDays: 10,
    capacityUtilization: 0.75,
    financialHealth: 80,
  },
  {
    id: "S3",
    label: "Guadalajara Power Trains",
    type: "subassembly",
    region: "Guadalajara, MX",
    volume: 2800,
    leadTimeDays: 10,
    bufferDays: 14,
    recoveryDays: 8,
    capacityUtilization: 0.69,
    financialHealth: 79,
  },
  {
    id: "S4",
    label: "Osaka Optics Assembly",
    type: "subassembly",
    region: "Osaka, JP",
    volume: 1700,
    leadTimeDays: 12,
    bufferDays: 10,
    recoveryDays: 11,
    capacityUtilization: 0.72,
    financialHealth: 85,
  },
  {
    id: "S5",
    label: "Chennai Chassis Works",
    type: "subassembly",
    region: "Chennai, IN",
    volume: 2300,
    leadTimeDays: 15,
    bufferDays: 9,
    recoveryDays: 13,
    capacityUtilization: 0.84,
    financialHealth: 71,
  },
  {
    id: "S6",
    label: "Porto Cable Assemblies",
    type: "subassembly",
    region: "Porto, PT",
    volume: 1400,
    leadTimeDays: 9,
    bufferDays: 16,
    recoveryDays: 7,
    capacityUtilization: 0.6,
    financialHealth: 83,
  },

  // Assembly plants
  {
    id: "F1",
    label: "Aurora Plant — Michigan",
    type: "factory",
    region: "Detroit, US",
    volume: 5200,
    leadTimeDays: 7,
    bufferDays: 11,
    recoveryDays: 9,
    capacityUtilization: 0.87,
    financialHealth: 90,
  },
  {
    id: "F2",
    label: "Meridian Plant — Bavaria",
    type: "factory",
    region: "Regensburg, DE",
    volume: 4700,
    leadTimeDays: 8,
    bufferDays: 13,
    recoveryDays: 8,
    capacityUtilization: 0.82,
    financialHealth: 91,
  },
  {
    id: "F3",
    label: "Pacifica Plant — Suzhou",
    type: "factory",
    region: "Suzhou, CN",
    volume: 6100,
    leadTimeDays: 9,
    bufferDays: 9,
    recoveryDays: 12,
    capacityUtilization: 0.94,
    financialHealth: 87,
  },

  // Distribution
  {
    id: "D1",
    label: "NA West DC",
    type: "distribution",
    region: "Reno, US",
    volume: 3400,
    leadTimeDays: 3,
    bufferDays: 21,
    recoveryDays: 4,
    capacityUtilization: 0.64,
    financialHealth: 92,
  },
  {
    id: "D2",
    label: "NA East DC",
    type: "distribution",
    region: "Columbus, US",
    volume: 3600,
    leadTimeDays: 3,
    bufferDays: 19,
    recoveryDays: 4,
    capacityUtilization: 0.67,
    financialHealth: 92,
  },
  {
    id: "D3",
    label: "EU Central DC",
    type: "distribution",
    region: "Venlo, NL",
    volume: 3900,
    leadTimeDays: 4,
    bufferDays: 22,
    recoveryDays: 5,
    capacityUtilization: 0.7,
    financialHealth: 90,
  },
  {
    id: "D4",
    label: "APAC Hub DC",
    type: "distribution",
    region: "Singapore, SG",
    volume: 4200,
    leadTimeDays: 5,
    bufferDays: 17,
    recoveryDays: 6,
    capacityUtilization: 0.79,
    financialHealth: 88,
  },
  {
    id: "D5",
    label: "LATAM DC",
    type: "distribution",
    region: "São Paulo, BR",
    volume: 2100,
    leadTimeDays: 6,
    bufferDays: 12,
    recoveryDays: 7,
    capacityUtilization: 0.73,
    financialHealth: 78,
  },
];

const nodes: SupplyNode[] = seeds.map(node);

const links: SupplyLink[] = [
  // raw -> component
  { source: "R1", target: "C1", volume: 2400 },
  { source: "R2", target: "C1", volume: 1200 },
  { source: "R3", target: "C2", volume: 1800 },
  { source: "R7", target: "C2", volume: 900 },
  { source: "R5", target: "C3", volume: 2200 }, // single source, high risk
  { source: "R4", target: "C4", volume: 1100 },
  { source: "R5", target: "C4", volume: 800 },
  { source: "R6", target: "C5", volume: 2600 },
  { source: "R7", target: "C6", volume: 1700 },
  { source: "R6", target: "C6", volume: 700 },
  { source: "R8", target: "C7", volume: 1500 }, // single source
  { source: "R4", target: "C8", volume: 800 },
  { source: "R3", target: "C8", volume: 600 },

  // component -> sub-assembly
  { source: "C1", target: "S1", volume: 2800 },
  { source: "C2", target: "S1", volume: 900 },
  { source: "C3", target: "S2", volume: 1600 },
  { source: "C4", target: "S2", volume: 800 },
  { source: "C6", target: "S3", volume: 1900 },
  { source: "C8", target: "S3", volume: 700 },
  { source: "C7", target: "S4", volume: 1300 }, // single source
  { source: "C5", target: "S5", volume: 2100 },
  { source: "C6", target: "S5", volume: 600 },
  { source: "C2", target: "S6", volume: 1200 },
  { source: "C3", target: "S6", volume: 500 },

  // sub-assembly -> factory
  { source: "S1", target: "F1", volume: 1800 },
  { source: "S3", target: "F1", volume: 1600 },
  { source: "S5", target: "F1", volume: 1200 },
  { source: "S2", target: "F2", volume: 1700 },
  { source: "S4", target: "F2", volume: 1100 },
  { source: "S6", target: "F2", volume: 900 },
  { source: "S1", target: "F3", volume: 2200 },
  { source: "S2", target: "F3", volume: 1400 },
  { source: "S5", target: "F3", volume: 1000 },

  // factory -> distribution
  { source: "F1", target: "D1", volume: 2400 },
  { source: "F1", target: "D2", volume: 2600 },
  { source: "F2", target: "D3", volume: 3100 },
  { source: "F2", target: "D2", volume: 900 },
  { source: "F3", target: "D4", volume: 3800 },
  { source: "F3", target: "D1", volume: 1000 },
  { source: "F1", target: "D5", volume: 1400 },
  { source: "F3", target: "D3", volume: 800 },
];

const scored = scoreNetwork({ nodes, links });

/** Network with model-derived risk scores. */
export const initialNetwork: SupplyNetwork = scored.network;
/** Per-node risk profile (factor breakdown, likelihood/impact split, absorption). */
export const riskIndex = scored.risk;

export const baseNodes: SupplyNode[] = nodes;
export const baseLinks: SupplyLink[] = links;
