/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as GeoRouteImport } from './routes/geo'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoRoute = GeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuppliersRoute,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SuppliersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/geo': typeof GeoRoute
  '/network': typeof NetworkRoute
  '/reports': typeof ReportsRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/suppliers/$id': typeof SuppliersIdRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/geo': typeof GeoRoute
  '/network': typeof NetworkRoute
  '/reports': typeof ReportsRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/suppliers': typeof SuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/geo': typeof GeoRoute
  '/network': typeof NetworkRoute
  '/reports': typeof ReportsRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/suppliers/$id': typeof SuppliersIdRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/geo'
    | '/network'
    | '/reports'
    | '/scenarios'
    | '/settings'
    | '/simulator'
    | '/suppliers'
    | '/suppliers/$id'
    | '/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/geo'
    | '/network'
    | '/reports'
    | '/scenarios'
    | '/settings'
    | '/simulator'
    | '/suppliers/$id'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/geo'
    | '/network'
    | '/reports'
    | '/scenarios'
    | '/settings'
    | '/simulator'
    | '/suppliers'
    | '/suppliers/$id'
    | '/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  GeoRoute: typeof GeoRoute
  NetworkRoute: typeof NetworkRoute
  ReportsRoute: typeof ReportsRoute
  ScenariosRoute: typeof ScenariosRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  SuppliersRoute: typeof SuppliersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo': {
      id: '/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof GeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof SuppliersRoute
    }
  }
}

interface SuppliersRouteChildren {
  SuppliersIdRoute: typeof SuppliersIdRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersIdRoute: SuppliersIdRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  GeoRoute: GeoRoute,
  NetworkRoute: NetworkRoute,
  ReportsRoute: ReportsRoute,
  ScenariosRoute: ScenariosRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  SuppliersRoute: SuppliersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
